{{- $config := tpl (.Files.Get "files/openrun.toml.tmpl") . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openrun.configSecretName" . }}
  labels:
    {{- include "openrun.labels" . | nindent 4 }}
stringData:
  openrun.toml: |
    {{- $config | nindent 4 }}
