apiVersion: v1
kind: Service
metadata:
  name: {{ include "openrun.fullname" . }}
  labels:
    {{- include "openrun.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "openrun.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.config.http.port  }}
      targetPort: http
      protocol: TCP
    {{- if .Values.config.https.enabled }}
    - name: https
      port: {{ .Values.config.https.port }}
      targetPort: https
      protocol: TCP
    {{- end }}
